use anyhow::{Context, Result};
use feed_rs::model::{Entry, FeedType};

use crate::db::NewArticle;

pub fn compute_article_id(feed_id: &str, unique_id: &str) -> String {
    let input = format!("{} {}", feed_id, unique_id);
    format!("{:x}", md5::compute(input.as_bytes()))
}

/// Match NNW's uniqueID generation exactly.
///
/// NNW uses: guid if present, rdf:about for RSS 1.0, or MD5(link+timestamp)
/// as fallback. feed-rs generates its own IDs when none exist in the feed,
/// so we detect those and replicate NNW's algorithm instead.
fn compute_unique_id(entry: &Entry, feed_type: &FeedType) -> String {
    if is_real_feed_id(&entry.id) {
        return entry.id.clone();
    }

    // RSS 1.0/RDF: NNW uses rdf:about (the item URL) as guid directly
    if matches!(feed_type, FeedType::RSS1) {
        if let Some(link) = entry.links.first() {
            return link.href.clone();
        }
    }

    // NNW's fallback chain: MD5 of the first non-empty combination
    let link = entry.links.first().map(|l| l.href.as_str()).unwrap_or("");
    let title = entry.title.as_ref().map(|t| t.content.as_str()).unwrap_or("");
    let date_str: Option<String> = entry
        .published
        .or(entry.updated)
        .map(|dt| format!("{}", dt.timestamp()));
    let body = entry
        .content
        .as_ref()
        .and_then(|c| c.body.as_deref())
        .or_else(|| entry.summary.as_ref().map(|s| s.content.as_str()))
        .unwrap_or("");

    let s = if !link.is_empty() && date_str.is_some() {
        format!("{}{}", link, date_str.as_ref().unwrap())
    } else if !title.is_empty() && date_str.is_some() {
        format!("{}{}", title, date_str.as_ref().unwrap())
    } else if let Some(ref d) = date_str {
        d.clone()
    } else if !link.is_empty() {
        link.to_string()
    } else if !title.is_empty() {
        title.to_string()
    } else {
        body.to_string()
    };

    format!("{:x}", md5::compute(s.as_bytes()))
}

/// Returns true if the ID looks like it came from the feed itself
/// (a URI, tag, or non-hex string) rather than being generated by feed-rs.
fn is_real_feed_id(id: &str) -> bool {
    if id.contains("://") || id.starts_with("urn:") || id.starts_with("tag:") {
        return true;
    }
    // feed-rs generates 31-32 char hex strings; anything with non-hex chars
    // or shorter than 28 chars is likely a real feed ID
    if id.len() < 28 {
        return true;
    }
    id.chars().any(|c| !c.is_ascii_hexdigit())
}

pub fn fetch_feed(url: &str) -> Result<Vec<NewArticle>> {
    let client = reqwest::blocking::Client::builder()
        .timeout(std::time::Duration::from_secs(30))
        .user_agent("NetNewsWire-CLI/0.1")
        .build()?;

    let resp = client
        .get(url)
        .send()
        .with_context(|| format!("Failed to fetch {}", url))?;
    let bytes = resp
        .bytes()
        .with_context(|| format!("Failed to read response from {}", url))?;

    let feed = feed_rs::parser::parse(&bytes[..])
        .with_context(|| format!("Failed to parse feed from {}", url))?;

    let feed_id = url.to_string();
    let feed_type = feed.feed_type;

    let articles: Vec<NewArticle> = feed
        .entries
        .into_iter()
        .map(|entry| {
            let unique_id = compute_unique_id(&entry, &feed_type);
            let article_id = compute_article_id(&feed_id, &unique_id);

            let title = entry.title.map(|t| t.content);

            let content_html = entry
                .content
                .as_ref()
                .and_then(|c| c.body.clone())
                .or_else(|| entry.summary.as_ref().map(|s| s.content.clone()));

            let content_text = content_html
                .as_ref()
                .map(|html| html2text::from_read(html.as_bytes(), 10000));

            let url = entry.links.first().map(|l| l.href.clone());

            let summary = entry.summary.map(|s| s.content);

            let image_url = entry
                .media
                .first()
                .and_then(|m| m.content.first())
                .and_then(|c| c.url.as_ref())
                .map(|u| u.to_string());

            let date_published = entry
                .published
                .or(entry.updated)
                .map(|dt| dt.timestamp() as f64);

            let authors_json = if entry.authors.is_empty() {
                None
            } else {
                let authors: Vec<serde_json::Value> = entry
                    .authors
                    .iter()
                    .map(|a| {
                        let name = &a.name;
                        let author_id = format!("{:x}", md5::compute(name.as_bytes()));
                        serde_json::json!({"name": name, "authorID": author_id})
                    })
                    .collect();
                Some(serde_json::to_string(&authors).unwrap())
            };

            NewArticle {
                article_id,
                feed_id: feed_id.clone(),
                unique_id,
                title,
                content_html,
                content_text,
                url,
                summary,
                image_url,
                date_published,
                authors_json,
            }
        })
        .collect();

    Ok(articles)
}
