use std::path::Path;

use anyhow::{Context, Result};

#[derive(Debug, Clone)]
pub struct Feed {
    pub text: String,
    pub xml_url: String,
    pub html_url: String,
}

#[derive(Debug, Clone)]
pub struct Folder {
    pub name: String,
    pub feeds: Vec<Feed>,
}

#[derive(Debug)]
pub struct Subscriptions {
    pub folders: Vec<Folder>,
}

impl Subscriptions {
    pub fn load(path: &Path) -> Result<Self> {
        let xml = std::fs::read_to_string(path)
            .with_context(|| format!("Failed to read OPML: {}", path.display()))?;
        let doc = roxmltree::Document::parse(&xml).context("Failed to parse OPML")?;

        let body = doc
            .descendants()
            .find(|n| n.tag_name().name() == "body")
            .context("No <body> in OPML")?;

        let mut folders = Vec::new();

        for outline in body.children().filter(|n| n.tag_name().name() == "outline") {
            if outline.attribute("xmlUrl").is_some() {
                // Top-level feed (no folder) — put in "Uncategorized"
                let feed = parse_feed_outline(&outline);
                let folder = folders
                    .iter_mut()
                    .find(|f: &&mut Folder| f.name == "Uncategorized");
                if let Some(folder) = folder {
                    folder.feeds.push(feed);
                } else {
                    folders.push(Folder {
                        name: "Uncategorized".to_string(),
                        feeds: vec![feed],
                    });
                }
            } else {
                let folder_name = outline
                    .attribute("text")
                    .or_else(|| outline.attribute("title"))
                    .unwrap_or("Unnamed")
                    .to_string();
                let feeds: Vec<Feed> = outline
                    .children()
                    .filter(|n| n.tag_name().name() == "outline")
                    .map(|n| parse_feed_outline(&n))
                    .collect();
                folders.push(Folder {
                    name: folder_name,
                    feeds,
                });
            }
        }

        Ok(Subscriptions { folders })
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        let mut out = String::new();
        out.push_str("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        out.push_str("<!-- OPML generated by NetNewsWire -->\n");
        out.push_str("<opml version=\"1.1\">\n");
        out.push_str("<head>\n\t<title>On My Mac</title>\n</head>\n");
        out.push_str("<body>\n");

        for folder in &self.folders {
            out.push_str(&format!(
                "\t<outline text=\"{}\" title=\"{}\">\n",
                xml_escape(&folder.name),
                xml_escape(&folder.name)
            ));
            for feed in &folder.feeds {
                out.push_str(&format!(
                    "\t\t<outline text=\"{}\" title=\"{}\" description=\"\" type=\"rss\" version=\"RSS\" htmlUrl=\"{}\" xmlUrl=\"{}\"/>\n",
                    xml_escape(&feed.text),
                    xml_escape(&feed.text),
                    xml_escape(&feed.html_url),
                    xml_escape(&feed.xml_url),
                ));
            }
            out.push_str("\t</outline>\n");
        }

        out.push_str("\t</body>\n</opml>\n");
        std::fs::write(path, &out)
            .with_context(|| format!("Failed to write OPML: {}", path.display()))?;
        Ok(())
    }

    pub fn all_feeds(&self) -> Vec<(&str, &Feed)> {
        self.folders
            .iter()
            .flat_map(|f| f.feeds.iter().map(move |feed| (f.name.as_str(), feed)))
            .collect()
    }

    pub fn feed_urls_in_folder(&self, folder_name: &str) -> Vec<String> {
        let name_lower = folder_name.to_lowercase();
        self.folders
            .iter()
            .filter(|f| f.name.to_lowercase() == name_lower)
            .flat_map(|f| f.feeds.iter().map(|feed| feed.xml_url.clone()))
            .collect()
    }

    pub fn feed_url_for_name(&self, name: &str) -> Option<String> {
        let name_lower = name.to_lowercase();
        self.all_feeds()
            .into_iter()
            .find(|(_, f)| f.text.to_lowercase() == name_lower)
            .map(|(_, f)| f.xml_url.clone())
    }

    pub fn feed_name_map(&self) -> std::collections::HashMap<String, String> {
        self.all_feeds()
            .into_iter()
            .map(|(_, f)| (f.xml_url.clone(), f.text.clone()))
            .collect()
    }

    pub fn add_feed(&mut self, feed: Feed, folder_name: Option<&str>) {
        let target = folder_name.unwrap_or("Uncategorized");
        if let Some(folder) = self.folders.iter_mut().find(|f| f.name == target) {
            folder.feeds.push(feed);
        } else {
            self.folders.push(Folder {
                name: target.to_string(),
                feeds: vec![feed],
            });
        }
    }

    pub fn remove_feed(&mut self, name_or_url: &str) -> bool {
        let lower = name_or_url.to_lowercase();
        for folder in &mut self.folders {
            let before = folder.feeds.len();
            folder.feeds.retain(|f| {
                f.text.to_lowercase() != lower && f.xml_url.to_lowercase() != lower
            });
            if folder.feeds.len() < before {
                return true;
            }
        }
        false
    }
}

fn parse_feed_outline(node: &roxmltree::Node) -> Feed {
    Feed {
        text: node
            .attribute("text")
            .or_else(|| node.attribute("title"))
            .unwrap_or("")
            .to_string(),
        xml_url: node.attribute("xmlUrl").unwrap_or("").to_string(),
        html_url: node.attribute("htmlUrl").unwrap_or("").to_string(),
    }
}

fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}
